### ISSUE TITLE
Incompatible with git gutter

### ISSUE THREAD

**Issue by unscene** [DavidLGoldberg/jum.py#30]
Jumpy: jump mode
Traceback (most recent call last):
  File "./sublime_plugin.py", line 195, in on_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 194, in <lambda>
  File "./git_gutter_events.py", line 18, in on_modified
  File "./view_collection.py", line 19, in add
  File "./git_gutter_handler.py", line 45, in reset
AttributeError: 'NoneType' object has no attribute 'run_command'
Jumpy: cancel
Jumpy: cancel
Jumpy: jumped to row: 26, col: 3, word: update
Jumpy: jump mode
Traceback (most recent call last):
  File "./sublime_plugin.py", line 339, in run_
  File "./jum.py", line 50, in run
  File "./index.py", line 30, in create_index
StopIteration

Hitting hotkey twice bombs out.

**Comment by DavidLGoldberg** [comment]
I have previously seen/figured this out.  All I remember is it was something I was going to do a pull request for his git gutter as it was something I thought he could be doing better. I'm going to put this off for a little bit, make sure everything is working without git gutter.  Also, I might be able to fix it on my end some how.
